/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.DBConnection;
import controller.Controller;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.ImgModel;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Kalum
 */
public class QuickBarcodeGen extends javax.swing.JPanel {

    private final DefaultTableModel model;
    Connection connection;

    /**
     * Creates new form QuickBarcodeGen
     */
    public QuickBarcodeGen() {
        initComponents();

        try {
            connection = DBConnection.getDBConnection().getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(QuickBarCodeGenn.class.getName()).log(Level.SEVERE, null, ex);
        }
        model = (DefaultTableModel) productTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        productNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        barcodeText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        descText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        noOfPrints = new javax.swing.JTextField();
        printBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(251, 251, 251));
        setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Product No");
        add(jLabel5);
        jLabel5.setBounds(10, 20, 90, 28);

        productNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNoActionPerformed(evt);
            }
        });
        productNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productNoKeyReleased(evt);
            }
        });
        add(productNo);
        productNo.setBounds(10, 50, 170, 28);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Bar Code No :");
        add(jLabel3);
        jLabel3.setBounds(10, 80, 90, 28);

        barcodeText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barcodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeTextActionPerformed(evt);
            }
        });
        add(barcodeText);
        barcodeText.setBounds(10, 110, 170, 28);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Desc");
        add(jLabel7);
        jLabel7.setBounds(10, 140, 90, 30);

        descText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descTextActionPerformed(evt);
            }
        });
        add(descText);
        descText.setBounds(10, 170, 170, 28);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Price");
        add(jLabel6);
        jLabel6.setBounds(10, 200, 90, 30);

        priceText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        priceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextActionPerformed(evt);
            }
        });
        add(priceText);
        priceText.setBounds(10, 230, 170, 28);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("No of prints :");
        add(jLabel2);
        jLabel2.setBounds(10, 260, 90, 28);

        noOfPrints.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noOfPrints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfPrintsActionPerformed(evt);
            }
        });
        add(noOfPrints);
        noOfPrints.setBounds(10, 290, 170, 28);

        printBtn.setText("Print");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        add(printBtn);
        printBtn.setBounds(110, 340, 70, 30);

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product No", "Barcode", "Description", "Price"
            }
        ));
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(200, 40, 450, 330);
    }// </editor-fold>//GEN-END:initComponents

    private void productNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNoActionPerformed
        String proNo = this.productNo.getText();
        System.out.println("xbnm");
        try {
            String sql = "select * from productBarCode where prono like '%" + proNo + "%'";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            model.setRowCount(0);
            while (resultSet.next()) {
                Object[] rowdata = {
                    resultSet.getString(1),
                    resultSet.getString(5),
                    resultSet.getDouble(4),
                    };
                model.addRow(rowdata);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GRNBarcodegenn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_productNoActionPerformed

    private void productNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productNoKeyReleased
        String proNo = this.productNo.getText();
        try {
            String sql = "select * from productBarCode where prono like '%" + proNo + "%'";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            model.setRowCount(0);
            while (resultSet.next()) {
                Object[] rowdata = {
                    resultSet.getString(1),
                    resultSet.getString(2),
                    resultSet.getString(3),
                    resultSet.getDouble(4),
                };
                model.addRow(rowdata);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GRNBarcodegenn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_productNoKeyReleased

    private void noOfPrintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfPrintsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfPrintsActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        Integer no = Integer.parseInt(noOfPrints.getText());
        ImgModel imgModel = new ImgModel();

        imgModel.setProNo(productNo.getText());
        imgModel.setBarcode(barcodeText.getText());
        imgModel.setBcdesc(descText.getText());
        imgModel.setCost(Float.valueOf(priceText.getText()));
        imgModel.setPrintQty(Integer.parseInt(noOfPrints.getText()));

        Controller controller = new Controller();
        try {
//            System.out.println("createBarcode");
//            controller.createBarcode(imgModel.getBarcode());
            System.out.println("saveBarcode");
            controller.saveBarcode(imgModel);
            System.out.println("viewBarcode");

            controller.viewJasperReport();
        } catch (JRException | SQLException ex) {
            Logger.getLogger(QuickBarcodeGen.class.getName()).log(Level.SEVERE, null, ex);
        }

        productNo.setText("");
        noOfPrints.setText("");

        //        try {
        //            createBarcode(no, barcode);
        //        } catch (ConfigurationException | BarcodeException | IOException ex) {
        //            System.out.println("Erro");
        //        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void barcodeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcodeTextActionPerformed

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        Integer selecRow = productTable.getSelectedRow();
        ImgModel imgModel = new ImgModel();
        imgModel.setProNo((String) model.getValueAt(selecRow, 0));
        imgModel.setBarcode((String) model.getValueAt(selecRow, 1));
        imgModel.setBcdesc((String) model.getValueAt(selecRow, 2));
        imgModel.setCost((double) model.getValueAt(selecRow, 3));
        productNo.setText(imgModel.getProNo());
        barcodeText.setText(imgModel.getBarcode());
        descText.setText(imgModel.getBcdesc());
        priceText.setText(model.getValueAt(selecRow, 3).toString());
    }//GEN-LAST:event_productTableMouseClicked

    private void priceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextActionPerformed

    private void descTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barcodeText;
    private javax.swing.JTextField descText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noOfPrints;
    private javax.swing.JTextField priceText;
    private javax.swing.JButton printBtn;
    private javax.swing.JTextField productNo;
    private javax.swing.JTable productTable;
    // End of variables declaration//GEN-END:variables
}
